### ISSUE TITLE
terminal background color while running emacs 

### ISSUE THREAD

**Issue by mohdalam** [purcell/emacs.d#262]
![little area](https://cloud.githubusercontent.com/assets/7526000/7214195/8d6caf4a-e5bd-11e4-817a-c13affd86411.png)
that green color small area how to remove that, (Running Ubuntu 14.04) and i am new to emacs.
![another](https://cloud.githubusercontent.com/assets/7526000/7214221/f3cd5ec8-e5be-11e4-8f96-62fa5a2f64de.png)
![screenshot from 2015-04-18 11 35 46](https://cloud.githubusercontent.com/assets/7526000/7214222/187785c8-e5bf-11e4-94ad-20fe6a674688.png)

**Comment by purcell** [comment]
Not sure, sorry. It doesn't do that for me on OS X with either iTerm or Terminal. Sometimes there's a little blank square at the bottom right. So I'm pretty sure there's nothing specific to this config which is causing the problem you're seeing.

The issue is probably related to either your terminal emulator and its `termcap` entries, or the version of Emacs you're running, or both.

Sorry I can't be more help. :-(

**Comment by mohdalam** [comment]
@purcell Thanks
