### ISSUE TITLE
Go further and add some basic functionality 

### ISSUE THREAD

**Issue by zell08v** [purcell/emacs.d#284]
Hi, 

People recommend me to use the init.el of S.Purcell as a starter kit for emacs newbies. So I have just installed it. 

I like this setting.  However, I do not know how to go further  from this init.el. I would like to

-- find an easy way to allow me to invoke more than 1 shells
-- make  'ispell' usable (currently,  I got 'no such file or directory, ispell' if I use 'M-X ispell)
-- make it easier to switch between windows. The c-x o key-stroke is not quite efficient. 

There are a lot of other basic functionality I would like to enable, but do not know the right way to get started. Any suggestions? Thanks. 

Zell

**Comment by purcell** [comment]
> -- find an easy way to allow me to invoke more than 1 shells

`C-u M-x shell` is standard, and pretty easy.

> -- make 'ispell' usable (currently, I got 'no such file or directory, ispell' if I use 'M-X ispell)

You need to install the `ispell` program.

> -- make it easier to switch between windows. The c-x o key-stroke is not quite efficient.

I've just added:

```
(windmove-default-keybindings 'control)
```

to the config, so that you can use Control + Arrows to switch windows. Some people also like to use `ace-jump` for this, which is bound to `C-;` in this config.

> There are a lot of other basic functionality I would like to enable, but do not know the right way to get started. Any suggestions? Thanks.

You can run `M-x customize` and browse the available settings. Also look on MELPA for interesting packages. To enable and configure some of those packages, you might need to add some elisp to your set-up files. The README has some information about that. If you have any specific questions, just let me know.
