### ISSUE TITLE
confused by html defaults

### ISSUE THREAD

**Issue by greaber** [purcell/emacs.d#301]
I have used Emacs for many years, but I have always found it a bit of a pain and never been very good at it.  I downloaded your config hoping it would give me a better starting place than my crufty old .emacs file.  I just tried to edit an HTML file, and I found the behavior confusing and am wondering if I am doing something wrong or just need to learn a few new habits or what.  Here is the file.  (Really any HTML file would work as an example.)

```
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width initial-scale=1">
    <style>
      div {
      width: 30px;
      }
    </style>
  </head>
  <body>
    ok
  </body>
</html>
```
1. The `<head>`, `<meta charset="utf-8">` and `<style>` lines seem to be flagged as errors of some kind because there is a question mark in the margin and tildes under where they begin.  But I can't find any indication of what is wrong with them.
2. Emacs doesn't indent the embedded css (nor will it indent embedded JavaScript).
3. There is an ugly red bar on the line beneath `ok` indicating that there is whitespace on that line, but when I press `tab` on that line, Emacs doesn't get rid of the whitespace but actually adds it back in if I remove it.
4. Pressing `tab` on other lines often pops up some kind of context menu instead of indenting the line.
5. It isn't doing nice things that I have seen in other editors like automatically adding closing tags or keeping the names of opening and closing tags in sync.

**Comment by purcell** [comment]
Thanks for this feedback!

> The <head>, <meta charset="utf-8"> and <style> lines seem to be flagged as errors of some kind because there is a question mark in the margin and tildes under where they begin. But I can't find any indication of what is wrong with them.

Those are flycheck errors, probably obtained from running `tidy` to lint the HTML. Display them either by putting your cursor on the underlined character, or with `M-x flycheck-list-errors`.

> Emacs doesn't indent the embedded css (nor will it indent embedded JavaScript).

That's a limitation of the built-in `html-mode`, and my config doesn't do anything to fix it. It's possible that `web-mode` will do the right thing here, but I haven't included it in my config because I don't personally need it.

> There is an ugly red bar on the line beneath ok indicating that there is whitespace on that line, but when I press tab on that line, Emacs doesn't get rid of the whitespace but actually adds it back in if I remove it.

I don't get that in this particular example, but that would generally be due to the `show-trailing-whitespace` setting. The whitespace will normally be cleaned up on save by `whitespace-cleanup-mode` (`WSC` in the modeline).

> Pressing tab on other lines often pops up some kind of context menu instead of indenting the line.

That's completion with `auto-complete`, which is a general feature of this config: it will trigger when you press TAB and emacs considers the current indentation of the line to be correct.

> It isn't doing nice things that I have seen in other editors like automatically adding closing tags or keeping the names of opening and closing tags in sync.

Yep, I confess that I haven't spent much time on the HTML config; I tend to work with other markup languages in most cases, so it's relatively rare for me to edit raw HTML extensively. I'll probably get around to improving things in due course. In the meantime, `tagedit` is installed and enabled, so you might look at the docs for that package, which will likely help make sense of the current behaviour.

Hope that helps a little - thanks so much for taking the time to write up this feedback.

**Comment by greaber** [comment]
And thanks for your response!  It is good to hear that other modes have received more attention.  If I figure out some improvements, I will send them on.

**Comment by purcell** [comment]
Super, thanks - I'd be happy to roll some improvement into the config, if only for the occasional times I need them myself. :-)
