### ISSUE TITLE
Can emacs delete obsolete package and upgrade to latest one in elpa at startup?

### ISSUE THREAD

**Issue by redguardtoo** [purcell/emacs.d#33]
two elpa questions:
1. how to automatically update package to the new version when it's available?
2. How to automatically remove the directory of old version of package automatically?

For example,
I installed `rinari-2.2` through elpa 3 months ago, I need emacs upgrade rinari to 2.6 ASAP. But I hate to `list-packages` to check when new version is release from time to time.

My purpose is make my elpa/ clean and find a easy way upgrade the packages I care.

**Comment by msx** [comment]
@GordonGustafson: I'm one of those folks that have a daemon running all the time :)
Did you ever found how to remove the obsolete packages? I'm quite interesting in the bit of code you pasted.

**Comment by GordonGustafson** [comment]
No, I never did get around to figuring out how to remove the packages. Also, that code broke in Emacs 24.4 due to `package-desc-vers` being replaced by `package-desc-version`. I thought the fix would be easy, but I remember struggling with it and never finding a solution.

I've since removed that code from my init file, and now I use `M-x list-packages` `U x`, which takes care of finding out of date packages and deleting old ones. I'm sure there exists a way to invoke this functionality on startup, but I'm pretty sure you'll have to actually open up a list-packages buffer to do it. If you're like me you'll find that you're updating packages on start because it's cool rather than because you need it.

**Comment by msx** [comment]
"If you're like me you'll find that you're updating packages on start because it's cool rather than because you need it." You are so damn right...
Anyways, good to read you and learn from your experience, thank you :)

**Comment by rprimus** [comment]
I've got a script that runs daily 'tasks' - one of which is updating elpa packages.  It relies on the package-utils elpa package.

Here is the (bash) function that handles this:

```bash
function upgrade_emacs_packages {
  echo 'upgrading emacs packages'
  emacs -batch -u "$USER" -f package-utils-upgrade-all -kill
}
```
This updates any packages and removes the old ones.

**Comment by msx** [comment]
Lovely hack @rprimus - works quite well indeed.

**Comment by aethanyc** [comment]
I use [paradox](https://github.com/Bruce-Connor/paradox) installed from melpa. It has a command <kbd>paradox-upgrade-packages</kbd> which upgrades all packages and delete the old ones.

**Comment by msx** [comment]
Thanks for the heads up Lin, didn't knew it :)

**Comment by jerome-diver** [comment]
packages-utils-upgrade-all is no more exist (and some other there)

this post is outdated and then obsolete.
It should be deleted for clarity and not make users waste time.

**Comment by jerome-diver** [comment]
@rprimus use what you want... i just use M-x package-install-packages then usual key bindings: U for update, d for select delete, etc... x for execute orders.
Nevermind, this thread is (again) obsolete and make waste time to users.

**Comment by purcell** [comment]
`M-x package-autoremove` is now built in.

**Comment by liar666** [comment]
When I do `M-x list-packages `, I see a lot of `obsolete` and `incompat` packages. Unfortunately, running `M-x package-autoremove` returns "Nothing to autoremove" :[

**Comment by purcell** [comment]
@liar666 Usually packages displayed as "obsolete" and "incompat" are not currently installed, so maybe the message is correct?

**Comment by bnsv** [comment]
> When I do `M-x list-packages `, I see a lot of `obsolete` and `incompat` packages. Unfortunately, running `M-x package-autoremove` returns "Nothing to autoremove" :[

I experienced the same. Some obsolete packages wont removed from the list but the new version is installed. It happens probably because I installing the new version without removing the old package. M-x Package-autoremove wont remove it, while other obsolete packages is disappear. But I am not sure.

**Comment by purcell** [comment]
Any examples of what packages are getting listed as "obsolete" and "incompat"?

**Comment by bnsv** [comment]
> Any examples of what packages are getting listed as "obsolete" and "incompat"?

Here is mine, the inf-ruby package.
![Screenshot from 2021-02-01 21-05-58](https://user-images.githubusercontent.com/25299811/106469468-ed78ee00-64d1-11eb-83f5-d01835dea8a9.png)

**Comment by purcell** [comment]
That's weird - upgraded packages should get removed automatically by package.el during upgrade.

**Comment by liar666** [comment]
Similar problem here with "realgud" :

![bug_emacs_pkg](https://user-images.githubusercontent.com/3216927/135637232-62e1f3c0-b675-46ae-b6b1-98feeb3287cd.png)

**Comment by purcell** [comment]
I note there's a specific command called `package-menu-mark-obsolete-for-deletion` for targeted clean-up of such packages, so perhaps this is due to a known edge case. I found I had a few obsolete packages locally too, just older versions of other installed packages from MELPA. Perhaps when a package install fails, it sometimes leaves older versions in place, unsure.
