### ISSUE TITLE
Little confusing

### ISSUE THREAD

**Issue by blithefeng** [purcell/emacs.d#418]
I have cloned this project into .emacs.d directory. When I start up emacs, nothing is changed I feel. 
Few steps I taken with this project.
Step 1. git clone https://github.com/purcell/emacs.d.git ~/.emacs.d
Step 2. step into .emacs.d and run test-startup.sh
Anything wrong with my usage?

**Comment by purcell** [comment]
`test-startup.sh` is for Travis, and the "Installation" section of the README doesn't say to use it: all you need to do is start up Emacs. But you're right, I can see how the name might be confusing.

The `test-startup.sh` script actually _does_ install all the elisp packages, but into a different package directory, which includes the emacs version in its name, e.g. `~/.emacs.d/elpa-24.5`.

I've just pushed a change to master so that the package directory _always_ includes the emacs version, so now the startup script will work the same way as just starting Emacs.
