### ISSUE TITLE
About your copyright

### ISSUE THREAD

**Issue by YuanPres** [purcell/emacs.d#445]
Hello:
I have seen your copyright license, but there are a few things that do not understand：

1.  I decided to leave your branch to customize it in depth.  So  Can I copy it directly for my repository instead of using “fork” ? (keeping your license)

2. Can I reauthorize it with license I like (just like “GPL” ) ? (But I will indicate the name and source of the original author (i.e. you) )

  
Because the Chinese people have been infringed by pirated software, so I am very vague on the copyright license. However, I am half a fanatical `free software` and GPL supporter.
So I asked this question.
  
If I have offended, please forgive me.
Thanks.

**Comment by purcell** [comment]
1. Yes, you can copy it, and this doesn't change the licence. But I would prefer if you fork, because it is a way of giving credit to me as the original author.

2. Please do not re-licence my code under different terms, sorry. If you add separate files, you could licence *those* individually under GPL, but if you simply modify my code, you can't really change the licence, because it will not have much effect, and it will be misleading: all the parts I published with a BSD licence will still be legally usable under that licence. BSD is also a widely-accepted open source licence, and I would suggest that you use it for this project, even if you generally prefer GPL.

**Comment by YuanPres** [comment]
Thanks. 
I will keep a fork.
Because I am prepared to write their own hands from now on.
But I am not experienced, so I borrowed your code.
I will gradually remove the code you have.I will not reauthorize before deciding which code is all prepared by me personally.

**Comment by YuanPres** [comment]
@purcell 
And... Can I use a GPL license for files that are written entirely by me?

**Comment by YuanPres** [comment]
@purcell 

Don't worry, I have deleted the project that constitutes your infringement (I have used the GPL license without your authorization).
I thought about it a few days,  I found that I still **CAN NOT** tolerate a BSD license. Even though I was copying yours rather than my original
I WILL NOT use your code without permission.

I am sorry for my ignorance and recklessness......
