### ISSUE TITLE
﻿Error (frameset): Font ‘-PfEd-DejaVu Sans Mono-bold-normal-normal-*-12-*-*-*-m-0-iso10646-1’ is not defined

### ISSUE THREAD

**Issue by davidpgil** [purcell/emacs.d#493]
I use your config between MacOS, Trisquel GNU/Linux and Windows 7. When I first open Emacs in Windows 7 after having just used Trisquel GNU/Linux I get the following error message:

`﻿Error (frameset): Font ‘-PfEd-DejaVu Sans Mono-bold-normal-normal-*-12-*-*-*-m-0-iso10646-1’ is not defined`

How may I stop this message from popping up? 

Also, I think it may be useful to someone out there to know why it pops up. Is Emacs expecting a certain font that doesn't exist?

Thanks for your fine work. Its a great starting point for me as a learner of Emacs and its workflow.

**Comment by purcell** [comment]
This is because `desktop.el` is saving info about your frames, and the saved font is not present on your Windows machine. You can either disable `desktop-save-mode`, avoid copying `~/.emacs.d/emacs.desktop` between machines, or adjust the settings of `desktop-save-mode` so that it doesn't store information about frames. Hope that helps!
