### ISSUE TITLE
error displaying unicode symbols in emacs

### ISSUE THREAD

**Issue by JCPD** [purcell/emacs.d#494]
Hi

First of all, thank for a really great config that I enjoyed very much using so far. I am experiencing problems with unicode characters (overall) in emacs (all buffers, all modes). To best show what I mean, the `M-x list-charset-chars RET unicode-bmp` looks like this:
![screen shot 2017-09-20 at 14 01 40](https://user-images.githubusercontent.com/19410932/30642736-520a2388-9e0c-11e7-82b3-7465ca5017f4.png)
I am running emacs on a Linux Red Hat distrubution through xterm.
The issue seems similar to one reported for spacemacs (where I experience the same problems) [https://github.com/syl20bnr/spacemacs/issues/211](url).
I am running GNU Emacs 25.2.1 and locale settings are en_US.UTF-8.
When I inspect the font with `M-x describe-font RET` it displays an XLFD:
-misc-fixed-medium-r-semicondensed--13-120-75-75-c-60-iso8859-1.

Any help is greatly appreciated as I have dealt with this issue for the last couple of days.
Thanks!

**Comment by purcell** [comment]
Yep, not sure, sorry. If you're using xterm, you're pretty much tied to xterm's font rendering, and it might not be able to pick and choose from different fonts in order to render all fonts. That will likely depend on how it was built, and on your window system and installed fonts. You could try using the GUI (GTK?) version instead, and see if that works better for you.
