### ISSUE TITLE
Debugger entered--Lisp error: (invalid-read-syntax "#")

### ISSUE THREAD

**Issue by sshaginyan** [purcell/emacs.d#544]
I get this message whenever I launch emacs.

`Debugger entered--Lisp error: (invalid-read-syntax "#")`
`read(#<buffer  *temp*>)`
`historian-load()`
`historian-mode(1)`
`ivy-historian-mode(t)`
`(closure (t) nil (ivy-historian-mode t))()`
`run-hooks(after-init-hook delayed-warnings-hook)`
`command-line()`
`normal-top-level()`

**Comment by purcell** [comment]
I've also seen this before, and my guess is that it is due to the [historian](https://github.com/PythonNut/historian.el) save file getting corrupted due to termination during saving, or _possibly_ due to inconsistent coding systems at save/load time. So it's nothing I can fix here, but to eliminate the former (more likely) failure mode @PythonNut might like to consider writing the new history to a temp file, then renaming it upon success. (The [current code](https://github.com/PythonNut/historian.el/blob/ba560443a216befd4460fcf16dc6c7f23cb73d8d/historian.el#L88-L91) just opens the existing save file and starts writing it.)

In the meantime, the workaround is to delete the historian file (`~/.emacs.d/.historian`).
