### ISSUE TITLE
Wrong colors on html-erb files using the desktop-session

### ISSUE THREAD

**Issue by masolino** [purcell/emacs.d#552]
Loading an `html-erb` file from a `desktop session` the colors of the themes are wrong while loading it with `--no-desktop` are shown correctly.

This happens with every theme.

I've done 2 screenshots:
with `desktop session` (wrong)
<img width="688" alt="desktop" src="https://user-images.githubusercontent.com/18376/37243868-bedb121a-2480-11e8-8df0-63c8f9fa1d06.png">
With `--no-desktop` (correct)
<img width="688" alt="no-desktop" src="https://user-images.githubusercontent.com/18376/37243879-f17aa578-2480-11e8-8844-b8f072acfb36.png">
Thanks

**Comment by purcell** [comment]
That's because it's in MMM (multiple major-mode) mode, and desktop.el doesn't really understand it - so what's happened is that when your desktop was saved, the major mode for the file was remembered as `ruby` because your point was in a ruby block at the time. You can see that in the modeline. So yes, this will happen sometimes, but it should be sufficient to say `M-x normal-mode` to reset things. Not sure that there's a general fix for this, or at least I can't currently think of a good one, sorry.

**Comment by masolino** [comment]
Ah ok, thanks
