### ISSUE TITLE
[Question] on using key-chords

### ISSUE THREAD

**Issue by azzamsa** [purcell/emacs.d#581]
Hi Mr. Purcell

Sorry for question. I want to ask your opinion about key-chords. 
I think using key-chord is very handy (push two keys rather than prefix+command keys). But I got little bit significant slow down in emacs for using key-chrods.

As long time Emacs user. You don't seems to use key-chord. 
Would you like to share your opinion on using key-chord in emacs ?

Thanks in advance.

**Comment by purcell** [comment]
Hi! I've never really tried using key chords. On the whole, I prefer to use fairly standard keybindings where possible, so that I'm not confused when I use Emacs on a different machine. I imagine key chords could be useful for building a memorable personal scheme for keybindings, since most "regular" key sequences are already used. :-)

**Comment by azzamsa** [comment]
Great. :)

Thank you for the explanation.

Happy Hacking.
