### ISSUE TITLE
js2 indent

### ISSUE THREAD

**Issue by InductionML** [purcell/emacs.d#705]
Firstly, thanks Steve for this it is really good to get such a great out of the box emacs config!

I'm a rank emacs newbie so this might be a stupid question, but with a clean install of this (moved all of my old `~/.emacs*` files out of the way) JS2 mode seems to indent with 4 spaces. Is that intentional and if so how do I change it to 2 spaces?

**Comment by purcell** [comment]
Ah, it works for me locally, but I see that's because js2-mode has different logic around its indent level variable in Emacs < 25, so you're probably using an older Emacs version than me. I've committed a fix which should help for you.

The more general answer to the question would have been to customise (or otherwise set) the `js2-basic-offset` to the desired indent width.
