### ISSUE TITLE
Would you like to consider using lsp-mode?

### ISSUE THREAD

**Issue by blueabysm** [purcell/emacs.d#746]
Currently `lsp-mode` is awesome. I've been using `lsp-mode` instead of `anaconda-mode` for weeks, it simplifies my configuration and make things consistent across golang/python/javascript/etc. Would you like to consider moving to `lsp-mode`😃?

**Comment by purcell** [comment]
> Would you like to consider moving to `lsp-mode`😃?

Yes, no and maybe.

I like the idea of LSP, and agree that it is the way of the future, but I don't particularly like `lsp-mode`, and would probably be more likely to use `eglot`.

I have trialled them both locally in my config over the last couple of years and haven't quite been 100% happy with either. I mostly use non-LSP mechanisms in the languages I work with, but I think this will change over time. For example, recently it's become clear that LSP is the only sane way to work with Elm in Emacs. I ended up hacking eglot to use flycheck instead of flymake, because I am still heavily invested in using flycheck consistently everywhere.

I won't commit either to the config until I'm a little happier with them, but you can rest assured that this is on my radar.

**Comment by Eason0210** [comment]
May be  you can have a try the light weight LSP client called [`Nox`](https://github.com/manateelazycat/nox) , which is a forked of `eglot`. It removed the dependency of `flymake` , and let  users to use `flycheck` by themself. And aslo removed other codes to keep the client light weight.   

The maintainer of `Nox` mainly use it with python, actually it also support other languages that eglot support. As I known, It works well on `Python`, `Haskell (with HLS)`, `Rust(with rust-analyzer or RLS)` and  `C++(with Clangd/ccls)`.

**Comment by purcell** [comment]
That's a good tip, thanks, I'll take a look when I get chance.

**Comment by purcell** [comment]
> May be you can have a try the light weight LSP client called [`Nox`](https://github.com/manateelazycat/nox) , which is a forked of `eglot`. It removed the dependency of `flymake` , and let users to use `flycheck` by themself. And aslo removed other codes to keep the client light weight.

I'm all in favour of cutting things down, but I would definitely want flycheck support via the LSP server, and at first glance it looks like there is no route to that with nox.

**Comment by Eason0210** [comment]
Yes，you are right. There is no flycheck support via Nox.

**Comment by purcell** [comment]
Here's where I'm at with this:

Locally, I'm actively using eglot. However, that *really* relies on flymake, and every other aspect of my config relies quite heavily on flycheck. There is code out there for getting eglot to report errors to flycheck, which has even been used by Doom Emacs, but that code is extremely hacky and unreliable (my fault - I think I was the first to share that abominable hack with the world).

So I've taken the opposite approach: I've written [flymake-flycheck](https://github.com/purcell/flymake-flycheck) so that I can use flymake instead of flycheck but still be able to use flycheck checkers. This is still quite clunky, so I haven't committed these changes to the public repo yet. It mostly works, but in many cases it results in redundant checkers. Also the auto-refreshing flycheck error list buffer is nicer than the flymake equivalent. Ultimately I need to do a bit more work on flymake-flycheck, probably to blocklist some checkers, and then I can consider pushing these changes.

**Comment by purcell** [comment]
Closing this now because my config for eglot is now included in this repo.
